# Configuración de MongoDB
spring:
  application:
    name: test2
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      uri: ${MONGODB_URI}    # Conexión a MongoDB. MONGODB_URI será pasada como variable de entorno en ECS.
      database: ${MONGO_DATABASE}    # Nombre de la base de datos en MongoDB
  jackson:
    serialization:
      write-dates-as-timestamps: false  # Serializar fechas en formato ISO en lugar de timestamps
  config:
    import: optional:file:.env[.properties]
# Configuración del servidor
server:
  port: 8080

# Configuración de logs
logging:
  level:
    root: INFO
    com.test.t2: DEBUG

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  ses:
    sourceEmail: ${EMAIL_FROM} # IMPORTANTE: En ambiente de sandBox deben estar verificados en AWS SES tanto el remitente, como el destinatario

# Swagger 
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true